plugin:
    name: 'mavitm.compon::lang.plugin.name'
    description: 'mavitm.compon::lang.plugin.description'
    author: MaviTm
    icon: oc-icon-pencil
    homepage: ''
permissions:
    mavitm.compon.access_accordion:
        tab: 'mavitm.compon::lang.accordion.tab'
        label: 'mavitm.compon::lang.accordion.access_post'
    mavitm.compon.access_carousel:
        tab: 'mavitm.compon::lang.carousel.tab'
        label: 'mavitm.compon::lang.carousel.access_post'
    mavitm.compon.access_tab:
        tab: 'mavitm.compon::lang.tab.tab'
        label: 'mavitm.compon::lang.tab.access_post'
navigation:
    main-menu-item:
        label: 'mavitm.compon::lang.plugin.name'
        url: mavitm/compon/compon
        icon: icon-list-alt
        permissions:
            - mavitm.compon.access_tab
            - mavitm.compon.access_carousel
            - mavitm.compon.access_accordion
        sideMenu:
            accordion_menu:
                label: 'mavitm.compon::lang.accordion.tab'
                url: mavitm/compon/accordion
                icon: icon-align-justify
                permissions:
                    - mavitm.compon.access_accordion
            carousel_menu:
                label: 'mavitm.compon::lang.carousel.tab'
                url: mavitm/compon/carousel
                icon: icon-arrows-h
                permissions:
                    - mavitm.compon.access_carousel
            tab_menu:
                label: 'mavitm.compon::lang.tab.tab'
                url: mavitm/compon/tab
                icon: icon-folder
                permissions:
                    - mavitm.compon.access_tab
