sublist:
    label: Alt değerler
    view:
        list: $/mavitm/compon/models/mtmdata/subimagesList.yaml
        toolbarButtons: create|delete
    manage:
        form: $/mavitm/compon/models/mtmdata/imgForm.yaml
        recordsPerPage: 100